import Pjax from 'theme-shokax-pjax';
export declare const CONFIG: configType;
export declare const statics: string;
export declare const scrollAction: {
    x: number;
    y: number;
};
export declare let diffY: number;
export declare let originTitle: string, titleTime: NodeJS.Timeout;
export declare const BODY: HTMLBodyElement;
export declare const HTML: HTMLElement;
export declare const Container: HTMLElement;
export declare const loadCat: HTMLElement;
export declare const siteNav: HTMLElement;
export declare const siteHeader: HTMLElement;
export declare const menuToggle: Element;
export declare const quickBtn: HTMLElement;
export declare const sideBar: HTMLElement;
export declare const siteBrand: HTMLElement;
export declare let toolBtn: HTMLElement;
export declare let toolPlayer: any;
export declare let backToTop: HTMLElement;
export declare let goToComment: any;
export declare let showContents: any;
export declare let siteSearch: HTMLElement;
export declare let siteNavHeight: number, headerHightInner: number, headerHight: number;
export declare let oWinHeight: number;
export declare let oWinWidth: number;
export declare let LOCAL_HASH: number;
export declare let LOCAL_URL: string;
export declare let pjax: Pjax;
export declare function setSiteNavHeight(value: number): void;
export declare function setHeaderHightInner(value: number): void;
export declare function setHeaderHight(value: number): void;
export declare function setOWinHeight(value: number): void;
export declare function setOWinWidth(value: number): void;
export declare function setDiffY(value: number): void;
export declare function setTitleTime(value: NodeJS.Timeout): void;
export declare function setLocalHash(value: number): void;
export declare function setLocalUrl(value: string): void;
export declare function setPjax(value: Pjax): void;
export declare function setOriginTitle(value: string): void;
export declare function setToolPlayer(value: any): void;
export declare function setBackToTop(value: HTMLElement): void;
export declare function setGoToComment(value: any): void;
export declare function setShowContents(value: any): void;
export declare function setToolBtn(value: HTMLElement): void;
export declare function setSiteSearch(value: HTMLElement): void;
